---
name: ChatRange
version: 0.0.1
main: minijaham\ChatRange\Main
api: 4.0.0
author: minijaham

commands:
  sudo:
    description: "Sudo a player!"
    permission: "command.sudo"

permissions:
  command.sudo:
    description: "Permission to sudo a player!"
    default: op
...
